name: Build & Push Docker Image  

on:  
  push:  
    branches: [main]  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Login to Docker Hub  
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  

      - name: Build Docker image  
        run: docker build -t myapp:latest .  

      - name: Tag Docker image  
        run: docker tag myapp:latest mydockerhubuser/myapp:latest  

      - name: Push Docker image  
        run: docker push mydockerhubuser/myapp:latest  