name: Deploy to Server  

on:  
  push:  
    branches: [main]  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Deploy via SSH  
        uses: appleboy/ssh-action@v0.1.10  
        with:  
          host: ${{ secrets.SERVER_HOST }}  
          username: ${{ secrets.SERVER_USER }}  
          key: ${{ secrets.SERVER_SSH_KEY }}  
          script: |  
            cd /var/www/my-app  
            git pull origin main  
            npm install  
            pm2 restart my-app  